redis-ha:
  enabled: false
  
## Repo Server
repoServer:
  env:   
    - name: VAULT_ADDR
      value: http://192.168.59.119:30709      

  # -- The number of repo server pods to run
  replicas: 1

  autoscaling:
    # -- Enable Horizontal Pod Autoscaler ([HPA]) for the repo server
    enabled: false

  ## Repo server metrics service configuration
  metrics:
    # -- Deploy metrics service
    enabled: false   
    serviceMonitor:
      # -- Enable a prometheus ServiceMonitor
      enabled: false     

server:     
  # -- The number of server pods to run
  replicas: 1

  autoscaling:
    # -- Enable Horizontal Pod Autoscaler ([HPA]) for the Argo CD server
    enabled: false
    
  ## Server metrics service configuration
  metrics:
    # -- Deploy metrics service
    enabled: false

    serviceMonitor:
      # -- Enable a prometheus ServiceMonitor
      enabled: false   


  additionalApplications: 
    - name: argocd-deploy-secret
      annotations:
        argocd.argoproj.io/sync-wave: "0"    
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        plugin:
          name: argocd-vault-plugin-helm  
          env:
            - name: HELM_VALUES
              value: |
                # global:   
                #   env: dev
                #   clusterName: bwb                  
        path: helm-charts
        repoURL: https://github.com/paas2/argo-deploy-secret.git
        targetRevision: dev               