server:     
  additionalApplications: 
    - name: argocd
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"      
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
          - values-base.yaml  
          - values-base-dev.yaml                    
          - values-build-dev.yaml
        path: helm-charts/argocd
        repoURL: https://github.com/paas2/argo.git
        targetRevision: dev                

    - name: infra-apps  
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"      
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml 
        path: apps
        repoURL: git@github.com:paas2/buildenv-infra-apps.git
        targetRevision: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true  
          
    - name: infra-app-projects
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"      
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: projects
        repoURL: git@github.com:paas2/buildenv-infra-apps.git  
        targetRevision: dev
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true          

    - name: build-apps
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"      
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml 
        path: apps
        repoURL: git@github.com:paas2/buildenv-apps.git
        targetRevision: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true    

    - name: build-app-projects
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"      
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: projects
        repoURL: git@github.com:paas2/buildenv-apps.git 
        targetRevision: dev
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true        