repoServer:
  env:   
    - name: AVP_K8S_MOUNT_PATH
      value: auth/sahab2-build-dev      
    - name: AVP_K8S_ROLE
      value: build-dev  
    - name: VAULT_ADDR
      value: http://192.168.59.133:30698 
    - name: AVP_TYPE
      value: vault  
    - name: AVP_AUTH_TYPE
      value: k8s   
                   
server:     
  additionalApplications: 
    - name: argocd-deploy-secret
      annotations:
        argocd.argoproj.io/sync-wave: "0"    
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        plugin:
          name: argocd-vault-plugin-helm  
          env:
            - name: HELM_VALUES
              value: |
                # global:   
                #   env: dev
                #   clusterName: bwb                  
        path: helm-charts
        repoURL: https://github.com/paas2/argo-deploy-secret.git
        targetRevision: dev  

    - name: argocd
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"      
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
          - values-base.yaml  
          - values-base-dev.yaml                    
          - values-build-dev.yaml
        path: helm-charts/argocd
        repoURL: git@github.com:paas2/argo.git
        targetRevision: dev   
                     

    - name: infra-apps  
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"      
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml 
          - values-dev.yaml           
        path: ./
        repoURL: git@github.com:paas2/buildenv-infra-apps.git
        targetRevision: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true  
          
    - name: infra-app-projects
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"      
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: projects
        repoURL: git@github.com:paas2/buildenv-infra-apps.git  
        targetRevision: dev
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true          

    - name: build-apps
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"      
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml 
        path: apps
        repoURL: git@github.com:paas2/buildenv-apps.git
        targetRevision: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true    

    - name: build-app-projects
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"      
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: projects
        repoURL: git@github.com:paas2/buildenv-apps.git 
        targetRevision: dev
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true        