redis-ha:
  enabled: false

  ## Repo Server
repoServer:     

  # -- The number of repo server pods to run
  replicas: 1

  autoscaling:
    # -- Enable Horizontal Pod Autoscaler ([HPA]) for the repo server
    enabled: false
    # -- Minimum number of replicas for the repo server [HPA]
    minReplicas: 2 

  ## Repo server metrics service configuration
  metrics:
    # -- Deploy metrics service
    enabled: false   
    serviceMonitor:
      # -- Enable a prometheus ServiceMonitor
      enabled: false 

server:     
  # -- The number of server pods to run
  replicas: 1

  autoscaling:
    # -- Enable Horizontal Pod Autoscaler ([HPA]) for the Argo CD server
    enabled: false
    # -- Minimum number of replicas for the Argo CD server [HPA]
    minReplicas: 2

  ## Server metrics service configuration
  metrics:
    # -- Deploy metrics service
    enabled: false

    serviceMonitor:
      # -- Enable a prometheus ServiceMonitor
      enabled: false

  additionalApplications: 
    - name: argocd
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
          - values-base.yaml  
          - values-base-dev.yaml                    
          - values-security-dev.yaml
        path: helm-charts/argocd
        repoURL: https://github.com/paas2/argo.git
        targetRevision: dev                

    - name: infra-apps  
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml 
        path: apps
        repoURL: https://github.com/paas2/security-infra-apps.git 
        targetRevision: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true  
          
    - name: infra-app-projects
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: projects
        repoURL: https://github.com/paas2/security-infra-apps.git  
        targetRevision: dev
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true          

    - name: securiy-apps
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml 
        path: apps
        repoURL: https://github.com/paas2-security/secyurity-apps.git
        targetRevision: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true    

    - name: security-app-projects
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: projects
        repoURL: https://github.com/paas2-security/secyurity-apps.git 
        targetRevision: dev
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true        